#!/usr/bin/env bash
# This script displays specific information from the /etc/passwd file.

# Using a while loop to read each line of /etc/passwd
while IFS=: read -r username password gid home shell; do
  # Extracting the user ID info
  uid_info=$(grep -E "^$username:" /etc/passwd | awk -F: '{print $5}')

  # Displaying formatted information
  echo "The user $username is part of the $gid gang,"
  echo "lives in $home and rides $shell."
  echo "USER ID's place is protected by the passcode $password,"
  echo "more info about the user here: $uid_info"
  echo "---------------------"
done < <(cat /etc/passwd)
