#!/usr/bin/env bash
# This script uses ssh to connect to a server using the private key ~/.ssh/school with the user ubuntu

# Ensure an IP address is provided as an argument
if [ -z "$1" ]; then
    echo "Usage: $0 <server_ip>"
    exit 1
fi

# Define the server IP from the first argument
server_ip=$1

# Connect to the server using ssh with the specified private key and user
ssh -i ~/.ssh/school ubuntu@"$server_ip"
